'
'
'Algemene programmadata
'
'
'
'Commando's
'
PROGDATA:
DATA oost,west,noord,zuid,klim,daal,gebruik,combineer,pak,leg,bekijk,afwachten,einde,status
'
'Voorvoegsels
'
DATA "in ","op ","bij ","de ","het ","een "
'
'Voorwerpen
'
'Namen voorwerpen
DATA "5vlees van de hellehond","5hittepak","5groene kristal","5zwaard","5bot","4diskette","4hasj","5rode kristal","4slaapmuts"
DATA "4noekietronenbom","4zaklamp","5verband","4vlammenwerper","5kookboek","4T.N.T.","5mosterdgaspatroon","5giftige vlees"
DATA "4ontsteking","4batterijen","5gasmasker","5papier","5boekje","5blauwe kristal","5koekje","4mosterdgasgranaat"
'Beschrijvingen voorwerpen
DATA "Het is een goor stuk vlees dat naar kots ruikt."
DATA "Dit aluminiumkleurig pak beschermt je tegen grote hitte of kou."
DATA "Het is een helder, groengekleurd kristal. Even zie je een mysterieuze twinke-*ling"
DATA "Het is een magisch zwaard dat er niet al te sterk uit ziet, maar veel kracht*uitstraalt. In het heft zit een paarse robijn."
DATA "Het is een menselijk, verbleekt dijbeen, dat er sterk uit ziet. Je kunt er veel*kracht mee zetten."
DATA "Het is een grijze 3,5 inch diskette van het merk 'Spirits' met daarop waar-*schijnlijk belangrijke data."
DATA "Het is een zakje met spul dat lijkt op tabak."
DATA "Het is een helder, roodgekleurd kristal. Even zie je een mysterieuze twinke-*ling."
DATA "Het is een Mickey Mouse-slaapmuts met vrolijke kleuren."
DATA "De bom bestaat uit een aantal dunne buizen in een cilinder. Daaromheen zitten*een aantal slangetjes. Er klinkt een vreemd gebrom dat uit een rooster komt. Er*zit een bordje op: -5 - 105ø, Codenaam: R136."
DATA "Het is een zwarte, aluminium zaklamp met een halogeenlampje erin."
DATA "Het is een witte doos met een rood kruis waarin wat verband en een paar pleis-*ters zitten."
DATA "De vlammenwerper bestaat uit een pijp, een zuur- en een brandstoffles en een*aktivatieknop. Uit de pijp komt een klein waakvlammetje."
DATA "Het is een oud, vergeeld kookboek met daarin een koekjesrecept. Er staat:*'Pak wat hellehond en wat hasj, en gooi het in de barbecue'.*Dat is alles."
DATA "De T.N.T. is een bosje rode staven met een velletje waarop staat: 'Pas op!*Schokgevoelig!'"
DATA "Het is een patroon dat mosterdgas onder druk bevat. Er zitten draadjes aan, en*je kunt niets vinden om hem te aktiveren."
DATA "Het is een stuk vlees dat er op zich lekker uit ziet, maar een paar groene*vlekken heeft. Er zit een dode mier op."
DATA "De ontsteking is een kastje met een T-vormige hendel erop."
DATA "Het is een pakketje met penlights. Konijntjes kunnen er uren mee trommelen."
DATA "Het is een groen masker met een rond filter en 2 plastic ooggaten."
DATA "Het is een geel vel papier met gekrulde hoeken. Het handschrift is bijna on-*leesbaar, en met moeite ontcijfer je: 'Voed de drakekop met de 3 gekleurde*kristallen'."
DATA "Het is een vies, kleverig boekje met op de voorkant een ontklede trol. Je*krijgt kotsneigingen."
DATA "Het is een helder, blauwgekleurd kristal. Even zie je een mysterieuze twinke-*ling."
DATA "Het is een rond koekje dat naar ammoniak stinkt."
DATA "Door het indrukken van de hendel kan het mosterdgas ontstnappen."
'Ruimtenummers meeneembare voorwerpen
DATA 0,5,0,6,14,21,23,0,25,28,32,40,41,44,0,52,53,61,62,63,0,71,73,0,0
'Nummers beesten waar voorwerpen op werken
DATA 9,0,13,0,7,12,9,13,5,14,0,0,10,0,0,0,4,0,0,0,0,2,13,5,6
'
'Ruimten
'
'==>'voorzetsel (1/2/3)''lidwoord (4/5/6)''ruimtenaam'
DATA "15bos","15bos","15bos","15moeras","15bos"
DATA "15bos","24begraafplaats","15bos","15moeras","24open plek"
DATA "15bos","15bos","24open plek","25moeraspad","24open plek"
DATA "15bos","15bos","24open plek","15moeras","14ru‹ne"

DATA "14slijmgrot","14zwarte grot","14drugsgrot","14geile grot","14jostiegrot"
DATA "14verwaarloosde grot","16lege grot","14hoofdgrot","14hierogliefengrot","14stankgrot"
DATA "14troosteloze grot","14TL-grot","14kleine grot","14ijsgrot","14kaktusgrot"
DATA "14stalagmietengrot","14stormgrot","14mistgrot","16wenteltrapgrot","14tentakelgrot"

DATA "14vuilnisgrot","14echogrot","14geheime grot","14voedselgrot","14grot van de gnoe"
DATA "16lege grot","14ogengrot","14rotsgrot","14leegte","14zandbank"
DATA "14martelgrot","16lege grot","14veilige grot","14nauwe rotsspleet","14oliegrot"
DATA "16lege grot","16wenteltrapgrot","14spinnengrot","14pratende grot","34lavaput"

DATA "14skoebiegrot","14radioactieve grot","14i-grot","14p-grot","14a-grot"
DATA "14dodengrot","14r-grot","14e-grot","16wenteltrapgrot","14P-grot"
DATA "14grot der verdoemenis","14vacuumgrot","14rode grot","14neongrot","14bloedgrot"
DATA "14vleermuisgrot","14slangengrot","14kwabbengrot","14glibbergrot","14teleportgrot"

'Ruimtebeschrijvingen
DATA "Je bevindt je in een uithoek van een donker bos. Overal hoor je enge geluiden."
DATA "Aan de zuidkant zie je een hek dat toegang geeft tot een donkere plaats."
DATA "Er komt een modderige geur uit het oosten."
DATA "Er hangt een griezelige nevel over het stinkende oppervlak."
DATA "Er komt een modderige geur uit het westen."
DATA "Pas op voor de laaghangende takken!"
DATA "Een lucht van rottend vlees dringt in je neus. Je denkt dat je een grafsteen*ziet bewegen."
DATA ""
DATA "Er hangt een griezelige nevel over het stinkende oppervlak."
DATA "Er komt een modderige geur uit het westen."
DATA ""
DATA "Je trapt bijna in een bereklem."
DATA "Door de mist zie je nog net de omtrekken van het donkere bos."
DATA "Er ligt hier een skelet, waarschijnlijk een van je voorgangers."
DATA "Bij het licht van een halve maan onderscheid je nog net de vorm van een galg."
DATA "In de verte hoor je het trieste gehuil van een weerwolf."
DATA ""
DATA "Er ligt hier een dood konijn dat wordt belaagd door vliegen."
DATA "Er hangt een griezelige nevel over het stinkende oppervlak."
DATA "Je bevindt je in een spookachtige ru‹ne. Er is hier een wankele trap die naar*beneden leidt."

DATA "De wanden van deze grot zijn bekleed met een snotachtig slijm."
DATA "Je ziet geen hand voor ogen."
DATA ""
DATA "Aan de muren hangen gelige, gescheurde Playboy-posters."
DATA "Er hangt hier een dwangbuis, met het lijk van een verminkte jostie."
DATA ""
DATA ""
DATA "Er staat hier een batterij aan mysterieuze apparatuur."
DATA "Op de wanden staan hierogliefen waar je geen wijs uit wordt."
DATA "Er hangt hier een smerige lucht die je herinnert aan de zware lucht van een*beerput."
DATA ""
DATA "De grot wordt zwak verlicht door een lichtbron die hoog aan het plafond hangt."
DATA "In het noorden zie je een dichte, zware deur met daarnaast een drakekop met*geopende muil en licht gloeiende ogen."
DATA "In deze grot lijkt het net of alles van ijs is, en je krijgt rillingen."
DATA "Je bent omringd door giftige kaktussen die in deze grot staan."
DATA "Hier zie je een traliewerk van stalagmieten."
DATA "Door deze grot loeit een harde wind, waardoor je je vast moet grijpen aan een*van de wanden."
DATA "Een dichte mist belemmert je zicht, en je verliest je or‹entatiegevoel."
DATA "In deze grot bevindt zich een grote, stenen wenteltrap die waarschijnlijk naar*andere niveaus leidt."
DATA "Van alle kanten komen grote tentakels die je aftasten en groene sporen op je*huid achterlaten."

DATA "In deze grot ligt een grote stapel rottende etensresten. De stank is bijna on-*draaglijk."
DATA "Hier worden alle geluiden die je maakt tegen de wanden ge‰cho'd."
DATA "Op de grond van deze grot liggen allerlei onbekende en geheimzinnige voorwer-*pen."
DATA "Zo te ruiken is dit waarschijnlijk eens een keuken geweest..."
DATA "Hier liggen de geraamtes van wezens die eerder ten prooi zijn gevallen aan de*gnoe."
DATA ""
DATA "Van alle kanten wordt je bespied door rode, bloeddoorlopen ogen die precies*volgen wat je doet."
DATA "Overal zie je hier scherpe rotspunten. Aan een aantal ervan zitten bruine kors-*ten."
DATA ""
DATA "Op de vloer liggen vreemde patronen, gevormd uit verschillende soorten zand."
DATA "Onder de vage schemering van de martelvuren zie je nog net een duimschroef en*wat stekelige voorwerpen waar nog wat bloed aan zit."
DATA ""
DATA "Dit is de enige grot waar je je een beetje veilig voelt."
DATA "Aan alle kanten wordt je omringd door hoge rotsmuren. Alleen in het westen zie*je een opening."
DATA "Vanuit het zuiden verspreidt zich een enorme hitte, die in deze grot nog net*draaglijk is."
DATA ""
DATA "In deze grot bevindt zich een grote, stenen wenteltrap die waarschijnlijk naar*andere niveaus leidt."
DATA "Het wemelt hier van de tarantula's. Bij elke stap die je zet hoor je het onder*je voeten kraken, en ze kruipen langs je benen omhoog."
DATA ""
DATA ""

DATA "Uit alle richtingen komen rare geluiden, als in een gesticht."
DATA "Door de hoge radioactiviteit is deze grot zwak verlicht."
DATA ""
DATA ""
DATA "In deze grot bevindt zich het stenen beeld van een oud, jou onbekend wezen."
DATA "De naam spreekt voor zich..."
DATA ""
DATA ""
DATA "In deze grot bevindt zich een grote, stenen wenteltrap die waarschijnlijk naar*andere niveaus leidt."
DATA ""
DATA "In deze grot heerst een haast verstikkende sfeer, en je voelt je niet prettig."
DATA ""
DATA ""
DATA "Deze grot is fel gekleurd. Er staan patronen die je doen denken aan zwarte ma-*gie."
DATA "Het geraamte van een groot beest ligt hier op de grond en een aantal ingewanden*liggen er naast."
DATA "In deze grot fladderen overal vleermuizen, op zoek naar hun prooi."
DATA "Je hoort het geluid van een ratelslang. Bij de weg naar het noorden staat een*doodskop getekend, die een gevaar aanduidt."
DATA ""
DATA "Je glijdt bijna uit over de zeepachtige prut die overal in de grot ligt. Tus-*sen de glibberige massa steekt een paal omhoog met daarop een pijl die naar*het oosten wijst."
DATA ""
'
'Niet meeneembare voorwerpen
'
'(Begin)ruimtenummers niet meeneembare voorwerpen
DATA 3,24,26,45,51,76,46,59,17,11,5,42,33,60,72,67
'Nodige slagen voor doden niet-meeneembare voorwerpen
DATA 2,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0
'
'Connecties tussen ruimten
'
'Verbindingen tussen lagen
DATA 4,6,52, 7,6,35, 9,6,31, 19,6,48, 20,6,22, 22,5,20, 29,6,59, 37,6,47, 39,6,57, 47,5,37, 57,5,39, 57,6,69, 59,5,29, 69,5,57, 80,5,2
'Versperde wegen en eenrichtingsverkeer
DATA 6,1, 7,2, 12,1, 13,2, 19,1, 20,2
DATA 21,1, 22,2, 23,1, 24,2, 24,1, 25,2, 26,1, 26,3, 27,2, 27,1, 28,2, 28,1, 29,2, 34,1, 35,2, 32,4, 37,3, 35,4, 40,3
DATA 41,1, 42,2, 42,1, 43,2, 43,1, 44,2, 44,1, 45,2, 46,3 47,1, 48,2, 53,1, 49,4, 54,3, 54,1, 55,2, 56,1, 57,2, 53,4, 58,3, 54,4, 59,1, 60,2
DATA 61,1, 62,2, 62,4, 67,3, 66,4, 71,3, 71,1, 72,2, 67,4, 72,3, 72,1, 73,2, 68,4, 73,3, 73,1, 74,2, 80,2, 75,4, 76,3, 80,3
'
''Papier'-route
'
DATA 70,65,64,63,68,67

