#include "headerku.h"

mulai()
awal
int bil, pangkat;
hapus();
cetak<<endl;
cetak<<"Program menghitung pangkat dua dan pangkat tiga"<<endl;
cetak<<"dari sebuah bilangan bulat dengan makro"<<endl;
cetak<<"----------------------------------"<<endl;
cetak<<"masukan bilangan bulat : ";masuk>>bil;//input bilangan bulat
cetak<<endl;
//pangkat 2
pangkat = PANGKAT2;
cetak<<"==================================="<<endl;
cetak<<"Pangkat dua dari"<<bil<<" adalah "<<pangkat;
cetak<<endl;
//pangkat 3
pangkat = PANGKAT3;
cetak<<"Pangkat tiga dari"<<bil<<" adalah "<<pangkat;
cetak<<"\n==================================="<<endl;
/**********************
borntobecode
***********************/
tahan();
akhir

