[sdl]
fullscreen=false
vsync=false

[render]
aspect=false

[dosbox]
machine=svga_s3

[cpu]
cycles=20000

[autoexec]
mount c /home/xor/nndecomp/msex/sopsw
mount d /home/xor/nndecomp/tc301  # Turbo C 3.01 installation
path=%PATH%;D:\BIN
set INCLUDE=D:\INCLUDE
set LIB=D:\LIB
c:
build_test.bat
