//***************************************************************************

#define N3DZ_BASE_1		0
#define N3DZ_TOWER_1 	1
#define N3DZ_DECK    	2
#define N3DZ_WIRES   	3
#define N3DZ_BALL    	4
#define N3DZ_BD_1    	5
#define N3DZ_BD_2    	6
#define N3DZ_BD_3    	7
#define N3DZ_BD_4    	8
#define N3DZ_BASE_2  	9
#define N3DZ_BASE_3  	10
#define N3DZ_TOWER_3 	11
#define N3DZ_TINY_CARR	12
#define N3DZ_WAKE    	13


#define N3DZ_L_COOLF14	14
#define N3DZ_LM_COOLF14	15
#define N3DZ_RM_COOLF14	16
#define N3DZ_R_COOLF14	17
#define N3DZ_L_MEDF14	18
#define N3DZ_C_MEDF14	19
#define N3DZ_R_MEDF14	20
#define N3DZ_DECK_F14	21
#define N3DZ_FLIGHT_F14	22
#define N3DZ_LTAIL		23
#define N3DZ_RTAIL		24

#define N3DZ_SIDEWIND	25
#define N3DZ_SPARROW	26
#define N3DZ_PHOENIX	27
#define N3DZ_FUELTANK	28
#define N3DZ_HARPOON	29
#define N3DZ_OLDSW		30
#define N3DZ_MK82		31

#define N3DZ_SHADOW		32
#define N3DZ_CHUTE		33
#define N3DZ_GATES		34
#define N3DZ_AAA		35
#define N3DZ_CANOPY		36

#define N3DZ_CHAFF		37
#define N3DZ_FLARE		38
