#define C_NORMAL 	0
#define C_ALTERNATE	1
#define C_QUIT		3

#define C_ADLIB 	0x10

#define C_LODMA		0x11
#define C_COVOX 	0x11
#define C_SB    	0x12

#define C_SBPROOLD	0x18
#define C_PAS		0x19

#define C_SBPRONEW  0x20
#define C_PASPLUS	0x21
#define C_GOLD		0x22
#define C_HIDMA		0x2F

#define C_ROLAND	0x30
#define C_LAPC		0x31

#define C_GM		0x38

#define C_SOUND_TYPES 11

