/*
**            Sound Numbers for F15 III
*/
#define N_AllOff           0 /* All Sounds Off */
#define N_AllFade          1 /* Graceful ending for All Sounds (1-6 on the Stack)*/
//#define N_MusicOff         2 /* Immediate ending for Background music */
//#define N_MusicFade        3 /* Graceful ending for Background music (1-6 on the Stack) */
#define N_NoiseOff         4 /* Immediate ending for Noise */
#define N_NoiseFade        5 /* Graceful ending for Noise (1-6 on the Stack)*/
#define N_Pause            6 /*  */
#define N_UnPause          7 /*  */
#define N_IsAnySoundOn     8 /* Is Any Sound Still On?? [ Flag in AX ] */
//#define N_TitleMus         9 
#define N_FarExplo        10 /* Distant or small Explo */
#define N_LoudExplo       11 /* Distant or small Explo */
#define N_WeGetHitExplo   12 /* Different Explo for us getting hit */
#define N_Cannon          13 /* (Continuous calling = repeated sound)*/
#define N_BlueWarning     14 /* Low Level Warning Sound (Continuous calling = repeated sound)*/
#define N_PurpleWarning   15 /* 2nd Level Warning Sound (Continuous calling = repeated sound)*/
#define N_YellowWarning   16 /* 3rd Level Warning Sound (Continuous calling = repeated sound)*/
#define N_OrangeWarning   17 /* 4th Level Warning Sound (Continuous calling = repeated sound)*/
#define N_RedWarning      18 /* Higest Level Warning Sound (Continuous calling = repeated sound)*/
#define N_SpoolUp         19 /* Engine Spools Up */
#define N_SpoolDown       20 /* Engine Spools Down */
#define N_FarMissile      21 /* Distant or small Missile Launch */
#define N_LoudMissile     22 /* Distant or small Missile Launch */
#define N_StallHorn       23 /* (Continuous calling = repeated sound)*/
#define N_DropChaff       24 /* */
#define N_DropBomb        25 /* */
#define N_Eject           26 /* */
#define N_OkJet           27 /* OK to have Jet Sound */
#define N_NoJet           28 /* No Jet Sound now */
#define N_KnotsAre        29 /* Jet Speed on Stack, 0 - 700 */
#define N_JetFromInside   30 /* Jet Sound Heard From Inside Cockpit */
#define N_JetFromOutside  31 /* Jet Sound Heard From Outside Cockpit */
#define N_PosFeedBack     32 /* Menu Feedback sound */
#define N_NegFeedBack     33 /* Menu Feedback sound */
#define N_AirBrakeOn      34 /* AirBrake Starts to move */
#define N_AirBrakeOff     35 /* Stop AirBrake Sound */
#define N_GearOpenSeq     36 /* Doors Open & Gear Moves until stopped by Close */
#define N_GearCloseSeq    37 /* Gear stops & Doors Close */
#define N_TireSqueal      38 /* Tires squeek on landing */
//#define N_FirstMedal      39 /* Music for winning 1st Medal */
//#define N_OtherMedals     40 /* Music for winning Other Medals */
//#define N_MedalOfHonor    41 /* Music for winning Medal of Honor */
//#define N_DeathMus        42 /* Player Dies */
//#define N_FeelGoodMus     43 /* Positive Feedback Music (alternates between two) */
//#define N_PromoMus        44 /* Promoted Music */
//#define N_WinCampaign     45 /* Win Campaign Music */
//#define N_ButtonClicks    46 /* Assorted Random Clicks */
//#define N_LockerOpen      47 /* Locker Door Opens  */
//#define N_LockerClose     48 /* Locker Door Closes */
//#define N_LargeDoorOpen   49 /* Office Door Opens  */
//#define N_SmallDoorOpen   50 /* Small Door Opens   */
//#define N_CanopyClose     51 /* F15 Canopy Closes  */
//#define N_SlidingSndOn    52 /* Start Sliding Sound */
//#define N_SlidingSndOff   53 /* Stop Sliding Sound */
//#define N_TelephoneSndOn  54 /* Start Telephone Sound */
//#define N_TelephoneSndOff 55 /* Stop Telephone Sound */
//#define N_TVStaticSndOn   56 /* Start TVStatic Sound */
//#define N_TVStaticSndOff  57 /* Stop TVStatic Sound */
//#define N_TrashBallDunk   58 /* Trash Ball Into Wastebasket */
//#define N_MetalBallClunk  59 /* Metal Ball Toy Noise */
//#define N_MetalBoxOpens   60 /* Open Metal Box Snd */
//#define N_F117Theme       61 /* F117 on TV Theme Music   */
//#define N_B17Theme        62 /* B17 on TV Theme Music   */
//#define N_GS2000Theme     63 /* GS2000 on TV Theme Music   */
//#define N_TaskTheme       64 /* TaskForce on TV Theme Music   */
//#define N_JetEntersRight  65 /* Jet Comes into view from Right */
//#define N_JetEntersLeft   66 /* Jet passes and exits Right */
#define N_LockOn          67 /* Target Lock */
#define N_SelectWeapon    68 /* Select Weapon on Weapon Screen */
#define MaxSnds           68 /* [Same as Last Sound]*/

