#define DECPOWER    0x0C2D
#define INCPOWER    0x0D3D
#define MINPOWER    0x0C5F
#define MAXPOWER    0x0D2B

#define TRIMDOWN	0x1A5B
#define	TRIMUP		0x1B5D
#define	TRIMSPD		0x1B7D
#define	TRIMSPD2	0x1B7B

#define PADPLUS     0x4E2B
#define PADMINUS    0x4A2D
#define PLUS        0x0D2B

#define F1KEY       0x3B00
#define F2KEY       0x3C00
#define F3KEY       0x3D00
#define F4KEY       0x3E00
#define F5KEY       0x3F00
#define F6KEY       0x4000
#define F7KEY       0x4100
#define F8KEY       0x4200
#define F9KEY       0x4300
#define F10KEY      0x4400

#define SF1KEY      0x5400
#define SF2KEY      0x5500
#define SF3KEY      0x5600
#define SF4KEY      0x5700
#define SF5KEY      0x5800
#define SF6KEY      0x5900
#define SF7KEY      0x5A00
#define SF8KEY      0x5B00
#define SF9KEY      0x5C00
#define SF10KEY     0x5D00

#define ALTF1KEY    0x6800
#define ALTF2KEY    0x6900
#define ALTF3KEY    0x6A00
#define ALTF4KEY    0x6B00
#define ALTF5KEY    0x6C00
#define ALTF6KEY    0x6D00
#define ALTF7KEY    0x6E00
#define ALTF8KEY    0x6F00
#define ALTF9KEY    0x7000
#define ALTF10KEY   0x7100

#define CTRLF1      0x5e00
#define CTRLF2      0x5f00
#define CTRLF3      0x6000
#define CTRLF4      0x6100
#define CTRLF5      0x6200

#define ALTAKEY     0x1e00
#define ALTBKEY     0x3000
#define ALTCKEY     0x2E00
#define ALTDKEY     0x2000
#define ALTEKEY     0x1200
#define ALTFKEY     0x2100
#define ALTGKEY     0x2200
#define ALTHKEY     0x2300
#define ALTIKEY     0x1700
#define ALTJKEY     0x2400
#define ALTKKEY     0x2500
#define ALTLKEY     0x2600
#define ALTMKEY     0x3200
#define ALTNKEY     0x3100
#define ALTOKEY     0x1800
#define ALTPKEY     0x1900
#define ALTQKEY     0x1000
#define ALTRKEY     0x1300
#define ALTSKEY     0x1F00
#define ALTTKEY     0x1400
#define ALTUKEY     0x1600
#define ALTVKEY     0x2F00
#define ALTWKEY     0x1100
#define ALTXKEY     0x2D00
#define ALTYKEY     0x1500
#define ALTZKEY     0x2C00

#define ALT0        0X8100
#define ALT1        0X7800
#define ALT2        0x7900
#define ALT3        0x7A00
#define ALT4        0x7B00
#define ALT5        0x7C00
#define ALT6        0x7D00
#define ALT7        0x7E00
#define ALT8        0x7F00
#define ALT9        0x8000
#define ALTMINUS    0x8200
#define ALTPLUS     0x8300

#define AKEY        0x1e61
#define BKEY        0x3062
#define CKEY        0x2e63
#define DKEY        0x2064
#define EKEY        0x1265
#define FKEY        0x2166
#define GKEY        0x2267
#define HKEY        0x2368
#define IKEY        0x1769
#define JKEY        0x246A
#define KKEY        0x256B
#define LKEY        0x266c
#define MKEY        0x326d
#define NKEY        0x316E
#define OKEY        0x186F
#define PKEY        0x1970
#define QKEY        0x1071
#define RKEY        0x1372
#define SKEY        0x1f73
#define TKEY        0x1474
#define UKEY        0x1675
#define VKEY        0x2F76
#define WKEY        0x1177
#define XKEY        0x2d78
#define YKEY        0x1579
#define ZKEY        0x2C7A

#define SHIFTA      0x1E41
#define SHIFTB      0x3042
#define SHIFTC      0x2E43
#define SHIFTD      0x2044
#define SHIFTE      0x1245
#define SHIFTF      0x2146
#define SHIFTG      0x2247
#define SHIFTH      0x2348
#define SHIFTI      0x1749
#define SHIFTJ      0x244A
#define SHIFTK      0x254B
#define SHIFTL      0x264C
#define SHIFTM      0x324D
#define SHIFTN      0x314E
#define SHIFTO      0x184F
#define SHIFTP      0x1950
#define SHIFTQ      0x1051
#define SHIFTR      0x1352
#define SHIFTS      0x1F53
#define SHIFTT      0x1454
#define SHIFTU      0x1655
#define SHIFTV      0x2F56
#define SHIFTW      0x1157
#define SHIFTX      0x2D58
#define SHIFTY      0x1559
#define SHIFTZ      0x2C5A

#define ESCKEY      0x011b
#define SPACEBAR    0x3920
#define ENTER       0x1C0D
#define BACKSPACE   0x0E08

#define INSERT      0x5200
#define DELETE      0x5300
#define HOME        0x4700
#define END         0x4F00
#define PAGEUP      0x4900
#define PAGEDOWN    0x5100

#define LEFTBRACK   0x1A5B
#define RIGHTBRACK  0x1B5D
#define BACKSLASH   0x2B5C
#define ACCENT      0x2960

#define LEFTANGLE   0x332C
#define RIGHTANGLE  0x342E
#define SLASH       0x352F
#define QUOTE       0x2827
#define SEMICOLON   0x273B

#define CTRLA		0x1e01
#define CTRLD		0x2004
#define CTRLE		0x1205
#define CTRLF		0x2106
#define CTRLL       0x260C
#define CTRLH		0x2308
#define CTRLQ		0x1011
#define CTRLR		0x1312
#define CTRLW		0x1117

#define KEY1        0x0231
#define KEY2        0x0332
#define KEY3        0x0433
#define KEY4        0x0534
#define KEY5        0x0635
#define KEY6        0x0736
#define KEY7        0x0837
#define KEY8        0x0938
#define KEY9        0x0A39
#define KEY0        0x0B30

#define SHIFT1      0x0221
#define SHIFT2      0x0340
#define SHIFT3      0x0423
#define SHIFT4      0x0524
#define SHIFT5      0x0625
#define SHIFT6      0x075E
#define SHIFT7      0x0826
#define SHIFT8      0x092A
#define SHIFT9      0x0A28
#define SHIFT0      0x0B29

#define PAD1        0x4F31
#define PAD2        0x5032
#define PAD3        0x5133
#define PAD4        0x4B34
#define PAD5        0x4C35
#define PAD6        0x4D36
#define PAD7        0x4737
#define PAD8        0x4838
#define PAD9        0x4939
#define PAD0        0x5230
#define PADDOT      0x532E

#define ZOOMKEY     ZKEY
#define UNZOOMKEY   XKEY

#define FIRE0KEY    ENTER
#define FIRE1KEY    SPACEBAR

//#define DECYKEY2    0x4800
//#define INCYKEY2    0x5000
//#define DECXKEY2    0x4B00
//#define INCXKEY2    0x4D00

#define UPARROW     0x4800
#define DOWNARROW   0x5000
#define LEFTARROW   0x4B00
#define RIGHTARROW  0x4D00

/****************************************************************************/
/*
/*  Special Pseudo-keys for passing commands for modem play
/*
/****************************************************************************/

#define RDRMOUSEACQ     0xFF01
#define HRMMOUSEACQ     0xFE01
#define HRMMOUSELOCK    0xFE02
#define AGMOUSEACQ      0xFD01
#define AGMOUSELOCK     0xFD02
#define HUDMOUSEACQ     0xFC01
#define TGTFLIRMOUSEACQ 0xFB01

