/*
**  SPEECH.H - speech defines for F14 Fleet Defender
**
**  update: 15.Oct.1993
*/

/* Pilot speech */

#define TARGETING           0
#define IM_HIT              1
#define GUNS                2
#define NOJOY               3
#define RTB                 4
#define FEETDRY             5
#define FEETWET             6
#define ENGAGE_DEF          7
#define WINCHESTER          8
#define CLEANCLEAR          9
#define TARGET_RANGE        10
#define NEGATIVE            11
#define ROGER               12
#define SINGERLAUNCH        13
#define SINGER              14
#define MUSIC               15
#define WERE_HIT            16
#define ALTITUDE            17
#define CONTACT             18
#define FOX1                19
#define FOX2                20
#define FOX3                21
#define SPIKE               22
#define LAUNCH              23
#define ZERO                24
#define ONE                 25
#define TWO                 26
#define THREE               27
#define FOUR                28
#define FIVE                29
#define SIX                 30
#define SEVEN               31
#define EIGHT               32
#define NINE                33
#define TEN                 34
#define C_20                35
#define C_30                36
#define C_40                37
#define C_80                38
#define C_120               39
#define C_160               40
#define C_200               41

/*  AWACS speech */

#define A_CLEAN             42
#define A_NOFACTOR          43
#define A_INVESTIGATE       44
#define A_VID               45
#define A_RED_FREE          46
#define A_CONTACT_BRG       47
#define A_RANGE             48
#define A_ZERO              49
#define A_ONE               50
#define A_TWO               51
#define A_THREE             52
#define A_FOUR              53
#define A_FIVE              54
#define A_SIX               55
#define A_SEVEN             56
#define A_EIGHT             57
#define A_NINE              58
#define A_TEN               59
#define A_20                60
#define A_30                61
#define A_40                62
#define A_80                63
#define A_120               64
#define A_160               65
#define A_200               66

/* LSO speech */

#define L_CALL_BALL         67
#define L_WAVE_OFF          68
#define L_BOLTER            69
#define L_ADD_POWER         70
#define L_REDUCE_POWER      71
#define L_COME_LEFT         72
#define L_COME_RIGHT        73
#define L_PADDLES           74
#define L_GOOD_JOB          75
#define L_CLRD_LAND         76
#define L_CUT_POWER         77
#define L_FIGHTS_ON         78
#define L_KNOCK_IT_OFF      79
#define L_YOURE_A_MORT      80
#define L_CLRD_TAKEOFF      81

