/*Latihan 1 Biodata Mahasiswa*/
#include<stdio>
#include<conio>
main()
{
printf("            BIODATA MAHASISWA\n");
printf("=============================================\n");
printf("NIM        = 11131517\n");
printf("NAMA       = San Shigatsu\n");
printf("KELAS      = 12.A1.07\n");
printf("TELEPHONE  = +6287612349867\n");
printf("ALAMAT     = 2062-1 Tonomachi Takeda, Takeda-shi, Oita-ken 878-0013\n");
printf("=============================================\n");
getch();
}
