void AllocGraphicPage() {}
void AvailSysMem() {}
void BuildSprite() {}
void Button() {}
void ChangeColor() {}
void CharWidth() {}
void ClearPage() {}
void ClipSprite() {}
void CloseSprite() {}
void DrawDot() {}
void DrawLine() {}
void DrawPoly() {}
void FontHeight() {}
void GETTIME() {}
void InitOverlay() {}
void LIBCANDO() {}
void LoadOverlay() {}
void LoadPalNoPic() {}
void LoadPalToPal() {}
void LoadPicGmem() {}
void LoadPicNoPal() {}
void LoadPicToPal() {}
void LoadPicture() {}
void MOUSE() {}
void MouseHIDE() {}
void MouseHITS() {}
void MouseOFF() {}
void MouseON() {}
void MouseSHOW() {}
void MouseTYPE() {}
void MouseX() {}
void MouseY() {}
void OpenSprite() {}
void RectCopy() {}
void RectFill() {}
void RpPrint() {}
void ScreenOff() {}
void ScreenOn() {}
void SetGraphicPage() {}
void Shake() {}
void ShowPage() {}
void SndShutdown() {}
void SndSounds() {}
void SndSysSetup() {}
void TurnOnGraphicsMode() {}
