/*Latihan 2 Pembelian Tiket Pesawat*/
#include<stdio>
#include<conio>
main()
{
printf("            Pembelian Tiket Pesawat\n");
printf("=============================================\n");
printf("No Transaksi               = 0001\n");
printf("Nama Lengkap               = Istianti Elyana\n");
printf("Kelas Penerbangan          = 1Eksekutif\n");
printf("No Kontak                  = 0856092587\n");
printf("Alamat Lengkap             = Jl Swadaya Indah No.25\n");
printf("Tanggal Pemberangkatan     = 12 Juli 2010\n");
printf("Harga                      = Rp. 250.000\n");
printf("Jumlah Beli                = 2 Tiket\n");
printf("Total                      = Rp. 500.000\n");
printf("=============================================\n");
getch();
}