/*-----------------------------*/
/*Inisialisasi Array Dimensi 1*/
/*-----------------------------*/
#include <conio.h>
#include <iostream.h>

main()
{
char hari [7][10]=
{"Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu"};
clrscr();
cout<<"Nama-nama hari :"<<endl;
cout<<hari[0]<<endl<<hari[1]<<endl<<hari[2]<<endl<<hari[3]<<endl<<hari[4]<<endl<<hari[5]<<endl<<hari[6]<<endl;
getch();
}