[sdl]
fullscreen=false
vsync=false

[render]
aspect=false

[dosbox]
machine=svga_s3

[cpu]
cycles=20000

[autoexec]
mount c /home/xor/nndecomp/msex/slashem
mount d /home/xor/nndecomp/msc5
path=%PATH%;D:\BIN
set INCLUDE=D:\INCLUDE
set LIB=D:\LIB
c:
d:\bin\nmake /f sys\msdos\Makefile.MSC